In [4]:
import numpy as np

In [8]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.ravel(x)
print y

[1 2 3 4 5 6]


In [6]:
print x

[[1 2 3]
 [4 5 6]]


In [13]:
type(x)

numpy.ndarray

In [15]:
z = np.random.random([3, 1])
print z

[[ 0.425377  ]
 [ 0.13017152]
 [ 0.69624172]]


In [12]:
np.random.random(3)

array([ 0.19429815,  0.86307406,  0.71959564])