In [15]:
import numpy as np
A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])
print (A)


B = A.sum(axis = 0)
print (B)

C = A / B
print (C)

B = A.sum(axis = 1)
print (B)

C = A / B.reshape([3, 1])
print (C)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]
[  59.   239.   155.4   76.9]
[[ 0.94915254  0.          0.02831403  0.88426528]
 [ 0.02033898  0.43514644  0.33462033  0.10403121]
 [ 0.03050847  0.56485356  0.63706564  0.01170351]]
[ 128.4  165.2  236.7]
[[ 0.43613707  0.          0.03426791  0.52959502]
 [ 0.00726392  0.62953995  0.31476998  0.04842615]
 [ 0.00760456  0.57034221  0.41825095  0.00380228]]


In [3]:
B

[56.0, 0, 0, 4, 4, 68.0, 1.2, 104.0, 52.0, 8.0, 1.8, 135.0, 99.0, 0.9]