In [2]:
import numpy as np

In [4]:
a = [1, 2, 3]
b = [4, 5, 6]
c = np.dot(a, b)
print (c)

32


In [6]:
a = np.array([[1, 2, 3],[1, 2, 3]])
b = np.array([4, 5, 6])
c = np.dot(a, b)
print (c)

[32 32]


In [27]:
a = np.array([[1, 2, 3],[1, 2, 3]])
b = np.array([4, 5])
c = np.dot(a, b)
print (c)

ValueError: shapes (2,3) and (2,) not aligned: 3 (dim 1) != 2 (dim 0)

In [28]:
a = np.array([[1, 2, 3],[1, 2, 3]])
b = np.array([4, 5])
c = np.dot(b, a)
print (c)

[ 9 18 27]


In [17]:
a = np.array([[1, 2, 3],[1, 2, 3]])
b = np.array([4, 5, 6])
c = np.matmul(a, b)
print (c)

[32 32]


In [23]:
a = np.array([[1, 2, 3],[1, 2, 3]])
b = np.array([[4], [5], [6]])
c = np.matmul(a, b)
print (c)

[[32]
 [32]]


In [24]:
a = np.array([[1, 2, 3],[1, 2, 3]])
b = np.array([[4], [5], [6]])
c = np.dot(a, b)
print (c)

[[32]
 [32]]


In [26]:
a = np.array([1, 2])
b = np.array([[2, 4, 6], [3, 5, 7]])
c = np.matmul(a, b)
print (c)

[ 8 14 20]


In [32]:
w = np.array([1, 2, 3])
b = np.array([[1, 1, 1, 1, 1], [2, 2, 2, 2, 2], [3, 3, 3, 3, 3]])
c = np.dot(w, b)
print (c)
d = np.dot(w.T, b)
print (d)

[14 14 14 14 14]
[14 14 14 14 14]


In [33]:
w.T

array([1, 2, 3])